<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 8 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary|ClinicalRecord)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record ((MetadataEntry|HeartRateVariabilityMetadataList)*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent|WorkoutRoute)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type         CDATA #REQUIRED
  date         CDATA #REQUIRED
  duration     CDATA #IMPLIED
  durationUnit CDATA #IMPLIED
>
<!ELEMENT WorkoutRoute ((MetadataEntry|Location)*)>
<!ATTLIST WorkoutRoute
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Location EMPTY>
<!ATTLIST Location
  date               CDATA #REQUIRED
  latitude           CDATA #REQUIRED
  longitude          CDATA #REQUIRED
  altitude           CDATA #REQUIRED
  horizontalAccuracy CDATA #REQUIRED
  verticalAccuracy   CDATA #REQUIRED
  course             CDATA #REQUIRED
  speed              CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
<!-- Note: Heart Rate Variability records captured by Apple Watch may include an associated list of instantaneous beats-per-minute readings. -->
<!ELEMENT HeartRateVariabilityMetadataList (InstantaneousBeatsPerMinute*)>
<!ELEMENT InstantaneousBeatsPerMinute EMPTY>
<!ATTLIST InstantaneousBeatsPerMinute
  bpm  CDATA #REQUIRED
  time CDATA #REQUIRED
>
<!ELEMENT ClinicalRecord EMPTY>
<!ATTLIST ClinicalRecord
  type              CDATA #REQUIRED
  identifier        CDATA #REQUIRED
  sourceName        CDATA #REQUIRED
  sourceURL         CDATA #REQUIRED
  fhirVersion       CDATA #REQUIRED
  receivedDate      CDATA #REQUIRED
  resourceFilePath  CDATA #REQUIRED
>
]>
<HealthData locale="en_CA">
 <ExportDate value="2019-09-05 12:44:38 -0230"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexNotSet" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c21950&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:14:47 -0230" startDate="2019-08-27 18:58:44 -0230" endDate="2019-08-27 18:58:44 -0230" value="82">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c21f40&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:24:13 -0230" startDate="2019-08-27 19:16:17 -0230" endDate="2019-08-27 19:16:17 -0230" value="85">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c21bd0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:24:13 -0230" startDate="2019-08-27 19:20:33 -0230" endDate="2019-08-27 19:20:33 -0230" value="79">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c21d10&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:27:31 -0230" startDate="2019-08-27 19:27:30 -0230" endDate="2019-08-27 19:27:30 -0230" value="88">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c21b30&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:27:35 -0230" startDate="2019-08-27 19:27:34 -0230" endDate="2019-08-27 19:27:34 -0230" value="75">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c218b0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:27:40 -0230" startDate="2019-08-27 19:27:38 -0230" endDate="2019-08-27 19:27:38 -0230" value="77">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c213b0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:27:45 -0230" startDate="2019-08-27 19:27:40 -0230" endDate="2019-08-27 19:27:40 -0230" value="78">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c21360&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:27:50 -0230" startDate="2019-08-27 19:27:49 -0230" endDate="2019-08-27 19:27:49 -0230" value="77">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c214f0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:27:55 -0230" startDate="2019-08-27 19:27:50 -0230" endDate="2019-08-27 19:27:50 -0230" value="76">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c21680&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:28:12 -0230" startDate="2019-08-27 19:23:39 -0230" endDate="2019-08-27 19:23:39 -0230" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22990&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:28:22 -0230" startDate="2019-08-27 19:28:21 -0230" endDate="2019-08-27 19:28:21 -0230" value="76">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22210&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:28:27 -0230" startDate="2019-08-27 19:28:26 -0230" endDate="2019-08-27 19:28:26 -0230" value="76">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22350&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:28:32 -0230" startDate="2019-08-27 19:28:28 -0230" endDate="2019-08-27 19:28:28 -0230" value="78">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22300&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:28:37 -0230" startDate="2019-08-27 19:28:32 -0230" endDate="2019-08-27 19:28:32 -0230" value="80">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c222b0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:29:54 -0230" startDate="2019-08-27 19:29:53 -0230" endDate="2019-08-27 19:29:53 -0230" value="110">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c235c0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:29:59 -0230" startDate="2019-08-27 19:29:54 -0230" endDate="2019-08-27 19:29:54 -0230" value="108">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c223f0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:30:03 -0230" startDate="2019-08-27 19:30:01 -0230" endDate="2019-08-27 19:30:01 -0230" value="75">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20be0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:30:08 -0230" startDate="2019-08-27 19:30:03 -0230" endDate="2019-08-27 19:30:03 -0230" value="74">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20a50&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:30:13 -0230" startDate="2019-08-27 19:30:11 -0230" endDate="2019-08-27 19:30:11 -0230" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20b40&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:37:23 -0230" startDate="2019-08-27 19:30:47 -0230" endDate="2019-08-27 19:30:47 -0230" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20aa0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:44:29 -0230" startDate="2019-08-27 19:35:52 -0230" endDate="2019-08-27 19:35:52 -0230" value="72">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c208c0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:44:30 -0230" startDate="2019-08-27 19:40:21 -0230" endDate="2019-08-27 19:40:21 -0230" value="73">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20960&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:58:44 -0230" startDate="2019-08-27 19:46:29 -0230" endDate="2019-08-27 19:46:29 -0230" value="74">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20d70&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:58:44 -0230" startDate="2019-08-27 19:48:48 -0230" endDate="2019-08-27 19:48:48 -0230" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20cd0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 19:58:44 -0230" startDate="2019-08-27 19:56:40 -0230" endDate="2019-08-27 19:56:40 -0230" value="68">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20dc0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:13:34 -0230" startDate="2019-08-27 19:58:38 -0230" endDate="2019-08-27 19:58:38 -0230" value="71">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20e60&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:13:34 -0230" startDate="2019-08-27 20:05:57 -0230" endDate="2019-08-27 20:05:57 -0230" value="70">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20eb0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:21:21 -0230" startDate="2019-08-27 20:08:47 -0230" endDate="2019-08-27 20:08:47 -0230" value="78">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20fa0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:29:29 -0230" startDate="2019-08-27 20:20:09 -0230" endDate="2019-08-27 20:20:09 -0230" value="80">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c21f90&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:29:30 -0230" startDate="2019-08-27 20:27:34 -0230" endDate="2019-08-27 20:27:34 -0230" value="81">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23610&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:44:30 -0230" startDate="2019-08-27 20:29:23 -0230" endDate="2019-08-27 20:29:23 -0230" value="82">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c20640&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:44:32 -0230" startDate="2019-08-27 20:34:43 -0230" endDate="2019-08-27 20:34:43 -0230" value="82">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23f70&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:55:58 -0230" startDate="2019-08-27 20:38:41 -0230" endDate="2019-08-27 20:38:41 -0230" value="82">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23d90&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:55:58 -0230" startDate="2019-08-27 20:45:58 -0230" endDate="2019-08-27 20:45:58 -0230" value="84">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23cf0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:55:58 -0230" startDate="2019-08-27 20:51:13 -0230" endDate="2019-08-27 20:51:13 -0230" value="86">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23f20&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 20:59:36 -0230" startDate="2019-08-27 20:57:54 -0230" endDate="2019-08-27 20:57:54 -0230" value="86">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22620&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:11:29 -0230" startDate="2019-08-27 21:01:06 -0230" endDate="2019-08-27 21:01:06 -0230" value="76">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22580&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:11:30 -0230" startDate="2019-08-27 21:07:30 -0230" endDate="2019-08-27 21:07:30 -0230" value="84">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22850&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:15:27 -0230" startDate="2019-08-27 21:11:08 -0230" endDate="2019-08-27 21:11:08 -0230" value="82">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22c10&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:17:59 -0230" startDate="2019-08-27 21:17:57 -0230" endDate="2019-08-27 21:17:57 -0230" value="85">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22cb0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:18:04 -0230" startDate="2019-08-27 21:18:02 -0230" endDate="2019-08-27 21:18:02 -0230" value="87">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22b70&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:18:09 -0230" startDate="2019-08-27 21:18:04 -0230" endDate="2019-08-27 21:18:04 -0230" value="88">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22da0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:18:14 -0230" startDate="2019-08-27 21:18:08 -0230" endDate="2019-08-27 21:18:08 -0230" value="89">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22e40&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:18:19 -0230" startDate="2019-08-27 21:18:14 -0230" endDate="2019-08-27 21:18:14 -0230" value="90">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c22f80&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:35:14 -0230" startDate="2019-08-27 21:16:28 -0230" endDate="2019-08-27 21:16:28 -0230" value="87">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23020&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:41:18 -0230" startDate="2019-08-27 21:34:56 -0230" endDate="2019-08-27 21:34:56 -0230" value="93">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c231b0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:44:18 -0230" startDate="2019-08-27 21:39:04 -0230" endDate="2019-08-27 21:39:04 -0230" value="80">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23250&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:48:18 -0230" startDate="2019-08-27 21:46:02 -0230" endDate="2019-08-27 21:46:02 -0230" value="74">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23480&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 21:53:52 -0230" startDate="2019-08-27 21:49:49 -0230" endDate="2019-08-27 21:49:49 -0230" value="74">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23390&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 22:05:43 -0230" startDate="2019-08-27 21:55:21 -0230" endDate="2019-08-27 21:55:21 -0230" value="76">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23430&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 22:14:30 -0230" startDate="2019-08-27 22:05:07 -0230" endDate="2019-08-27 22:05:07 -0230" value="75">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23700&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 22:14:32 -0230" startDate="2019-08-27 22:09:37 -0230" endDate="2019-08-27 22:09:37 -0230" value="84">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c237a0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 22:18:54 -0230" startDate="2019-08-27 22:14:06 -0230" endDate="2019-08-27 22:14:06 -0230" value="62">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23840&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 22:29:30 -0230" startDate="2019-08-27 22:20:09 -0230" endDate="2019-08-27 22:20:09 -0230" value="76">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="0"/>
 </Record>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Daniel’s Apple Watch" sourceVersion="5.1.1" device="&lt;&lt;HKDevice: 0x283c23a20&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:5.1.1&gt;" unit="count/min" creationDate="2019-08-27 22:29:31 -0230" startDate="2019-08-27 22:27:17 -0230" endDate="2019-08-27 22:27:17 -0230" value="78">
  <MetadataEntry key="HKMetadataKeyHeartRateMotionContext" value="1"/>
 </Record>